export const API_ENDPOINTS = {
    LOGIN: "/auth/client/signin",
    SIGNUP: "/auth/client/signup",
    GET_ACCESS_TOKEN: "/auth/getToken",
    GET_OTP: "/auth/get-otp",
    GET_USER_PROFILE: "/user/getUserProfile",
    LOGOUT: "/logout",
    FORGET_PASSWORD: "/forget-password",
    CATEGORIES: "/api/categories.json",
    FEATURED_CATEGORIES: "/featured_categories.json",
    COLLECTIONS: "/collections.json",
    BRANDS: "/api/brands.json",
    PRODUCTS: "/api/products.json",
    FEATURED_PRODUCTS: "/featured_products.json",
    TOP_SELLER_PRODUCTS: "/products_top_seller.json",
    ON_SELLING_PRODUCTS: "/products_on_selling.json",
    PRODUCT: "/api/product.json",
    RELATED_PRODUCTS: "/api/related_products.json",
    BEST_SELLER_PRODUCTS: "/products_best_seller.json",
    NEW_ARRIVAL_PRODUCTS: "/products_new_arrival.json",
    FLASH_SALE_PRODUCTS: "/products_flash_sale.json",
    SEARCH: "/search.json",
    ORDERS: "/api/orders.json",
    ORDER: "/api/order.json",
};
