image: node:latest

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "master"'
      when: always


stages:
  - checkout-master
  - cache-check
  - build
  - test
  - deploy

cache:
  key: $CI_COMMIT_REF_SLUG
  # key:
  #  files:
  #     - Gemfile.lock
  #     - package.json
  paths:
    - node_modules/
    - .yarn


Get yarn cache directory path:
  stage: cache-check
  script:
   - echo "::set-output name=dir::$(yarn cache dir)"


Checkout Branch:
  stage: checkout-master
  variables:
    GIT_STRATEGY: fetch
    GIT_CHECKOUT: "false"
  script:
    - git checkout -B master origin/master


Install dependencies:
   stage: build
   script:
       - yarn


# Run Lint:
#    stage: build
#    script:
#        - yarn lint

Run tests:
   stage: test
   script:
       - yarn test
       
Run e2e test:
   stage: test
   script:
       - yarn cypress:test       