default:
  image: node:14.17.1

# variables:
#   CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "master"'
      when: always


stages:
  - checkout-master
  - cache-check
  - build
  - lint
  - test
  - deploy

cache:
  key: $CI_COMMIT_REF_SLUG
  # key:
  #  files:
  #     - Gemfile.lock
  #     - package.json
  paths:
    - node_modules/
    - .yarn
    # - cache/Cypress
    - build


Get yarn cache directory path:
  stage: cache-check
  script:
   - echo "::set-output name=dir::$(yarn cache dir)"


Checkout Branch:
  stage: checkout-master
  variables:
    GIT_STRATEGY: fetch
    GIT_CHECKOUT: "false"
  script:
    - git checkout -B master origin/master


Install dependencies:
   stage: build
   script:
       - yarn
       - cypress install


Run Lint:
   stage: lint
   script:
       - yarn lint

Run tests:
   stage: test
   script:
       - yarn test
       
Run e2e test:
   stage: test
   script:
       - npx cypress cache path
       - npx cypress cache list
       - yarn cypress:test       