export const ROUTES = {
    HOME: "/",
    PRODUCT: `/products`,
    CHECKOUT: "/checkout",
    CONTACT: "/contact-us",
    TERMS: "/terms",
    POLICY: "/privacy",
    FAQ: "/faq",
    FORGET_PASSWORD: "/forget-password",
    ACCOUNT: "/my-account",
    ORDERS: "/my-account/orders",
    ACCOUNT_DETAILS: "/my-account/account-details",
    ACCOUNT_FAVORITES: "/my-account/account-favorites",
    CHANGE_PASSWORD: "/my-account/change-password",
    SHOP: "/shop",
    CART: "/cart",
    LOGIN: "/signin",
    SIGN_UP: "/signup",
    SEARCH: "/search",
    HANG_MOI_VE: "/hang-moi-ve",
    COLLECTIONS: "/collections",
    PROMOTIONS: "/promotions",
    SERVICES: "/dich-vu",
    CATEGORY: "/category",
    ORDER: "/order",
};
